SELECT * FROM USER_INFO UI,
CLASS_INFO CI
WHERE CI.CINO=UI.CINO;
SELECT * FROM USER_INFO;

CREATE TABLE TEMP_CU AS
SELECT DATE_FORMAT(NOW(), '%H시-%I분-%S초'), CI.CINAME, CI.CIDESC FROM CLASS_INFO CI,
USER_INFO UI
WHERE CI.CINO=UI.CINO;

SELECT * FROM TEMP_CU;

DROP TABLE TEMP_CU;

SELECT * FROM V_UI_CI
WHERE UINAME='홍길동'
OR UINAME='금길동';

CREATE VIEW V_UI_CI AS
SELECT UI.*, CI.CINAME, CI.CIDESC FROM USER_INFO UI,
CLASS_INFO CI
WHERE UI.CINO=CI.CINO;

SELECT * FROM V_UI_CI;

CREATE VIEW VVV AS
SELECT * FROM V_UI_CI;

SELECT * FROM VVV;

DROP VIEW VVV;

DROP PROCEDURE P_INSERT_CLASS_INFO;

DELIMITER $$
CREATE PROCEDURE P_INSERT_CLASS_INFO(
IN P_CINAME VARCHAR(100), P_CIDESC VARCHAR (500))
BEGIN
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1
		@ER_NO=RETURNED_SQLSTATE, @ER_MSG=MESSAGE_TEXT;
		SELECT @ER_NO, @ER_MSG;
		ROLLBACK;
	END;
	START TRANSACTION;
	INSERT INTO CLASS_INFO(CINAME,CIDESC)
	VALUES(P_CINAME, P_CIDESC);
	COMMIT;
	SELECT * FROM CLASS_INFO;
END
$$ 
DELIMITER ;

CALL P_INSERT_CLASS_INFO('TEST','TESTR');