
DELIMITER $$
CREATE PROCEDURE p_insert_user_info
(IN P_UINAME VARCHAR(100),P_UIAGE TINYINT,P_UIID VARCHAR(100),
P_UIPWD VARCHAR(100))
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1
		@ER_NO= RETURNED_SQLSTATE, @ER_MSG=MESSAGE_TEXT;
		SELECT @ER_NO, @ER_MSG;
		ROLLBACK;
	END;
	START TRANSACTION;
	INSERT INTO USER_INFO(ID,PWD,NAME,AGE,CLASS_NUM)
	VALUES(P_UIID,P_UIPWD,P_UINAME,P_UIAGE,3);
	COMMIT;
	SELECT * FROM USER_INFO;
END
$$ 
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE p_test
(IN P_UINAME VARCHAR(100),P_UIAGE TINYINT,P_UIID VARCHAR(100),
P_UIPWD VARCHAR(100))
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1
		@ER_NO= RETURNED_SQLSTATE, @ER_MSG=MESSAGE_TEXT;
		SELECT @ER_NO, @ER_MSG;
		ROLLBACK;
	END;
	START TRANSACTION;
	SET @T:=1;
	WHILE @T<4 DO
	INSERT INTO USER_INFO(ID,PWD,NAME,AGE,CLASS_NUM)
	VALUES(P_UIID,P_UIPWD,P_UINAME,P_UIAGE,3);
	SET @T:=@T+1;
	END WHILE;
	COMMIT;
	SELECT * FROM USER_INFO;
END
$$ DELIMITER ;


drop PROCEDURE p_test;

CALL p_test("ㅎㅇ",33,"id","pwd");
DESC USER_INFO;

SELECT * FROM USER_INFO
WHERE UINO<10;


CREATE TABLE USER_INFO(
NO INT AUTO_INCREMENT PRIMARY KEY,
ID VARCHAR (100),
PWD VARCHAR (100),
NAME VARCHAR (100),
AGE INT,
CLASS_NUM INT);

INSERT INTO USER_INFO(ID,PWD,NAME,AGE,CLASS_NUM)
VALUES('RED','RED','홍길동',30,1),
('BLUE','BLUE','청길동',15,2),
('GREEN','GREEN','녹길동',20,2),
('BLACK','BLACK','흑길동',40,2);

SELECT * FROM USER_INFO
WHERE CLASS_NUM BETWEEN 1 AND 2;

SELECT * FROM USER_INFO
WHERE SUBSTR(ID,1,1) IN ('B','A');

SELECT * FROM USER_INFO
WHERE CLASS_NUM IN (1,2) AND AGE>=30;